spring.application.name=pashuKalyan
spring.security.user.name=nuhang
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pashu_kalyan_db
spring.datasource.username=postgres
spring.datasource.password=nuhang
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.servlet.session.timeout=30m

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

